### ISSUE TITLE
Can't Find golint & goimports

### ISSUE THREAD

**Issue by sha256x** [yields/sublime-go#10]
OS: Mojave
Go: 1.12.9

Installed:
golang.org/x/lint/golint
golang.org/x/tools/cmd/goimports
github.com/nsf/gocode
golang.org/x/tools/cmd/guru

Get errors:
FileNotFoundError: [Errno 2] No such file or directory: 'golint'
FileNotFoundError: [Errno 2] No such file or directory: 'goimports'

Anything I'm missing from a setup?

I installed the tool by importing the repo into the package manager and installing it from there.

**Comment by yields** [comment]
Maybe `golint` and `goimports` are not in your sublime path? 

you can check this via the console with `import os; os.environ.get('PATH')`.
you can also try and run those tools from the command line to see if they're there.

**Comment by yields** [comment]
Closing, feel free to re-open!

**Comment by sha256x** [comment]
No, it seems `GOPATH` and `GOROOT` are not in `import os; os.environ.get('PATH')`. Best practice to add this in Sublime text? I've got `GOROOT` and `GOPATH` in `PATH` set in `~/.zshrc`

**Comment by yields** [comment]
Still, when `go(1)` itself can be reached by the plugin, it should be using `go env` output to set the env before calling external commands like `golint(1)`.

Can you run the following from the console when you have a go file open?

```py
import Golang.go.exec as exec; 
import os.path as path; 
exec.goenv(path.dirname(view.file_name())).then(lambda v: print(v))
```

It'd be great if we can solve this, getting the plugin to work across all environments is hard but worth it :)

**Comment by yields** [comment]
You can also try the latest version, it automatically adds [GOPATH into PATH](https://github.com/yields/sublime-go/commit/49badedbd23f57765ffab62b587e373e89fb771c).

**Comment by yields** [comment]
I think this is fixed in v0.0.3, just add the repo and install v0.0.3.
lmk if this is still causing issues! :)

**Comment by sha256x** [comment]
> Still, when `go(1)` itself can be reached by the plugin, it should be using `go env` output to set the env before calling external commands like `golint(1)`.
> 
> Can you run the following from the console when you have a go file open?
> 
> ```python
> import Golang.go.exec as exec; 
> import os.path as path; 
> exec.goenv(path.dirname(view.file_name())).then(lambda v: print(v))
> ```
> 
> It'd be great if we can solve this, getting the plugin to work across all environments is hard but worth it :)

I tried the latest version of the plugin `0.0.4` and ran the command and got this:
```
>>> import Golang.go.exec as exec; 
>>> import os.path as path; 
>>> exec.goenv(path.dirname(view.file_name())).then(lambda v: print(v))
Traceback (most recent call last):
  File "<string>", line 1, in <module>
AttributeError: 'dict' object has no attribute 'then'
```

Unfortunately the latest version doesn't seem to have added GOPATH. Let me know how I can help!
Would be cool to get this fixed.

**Comment by yields** [comment]
Whoops sorry, no `then()` is needed.

```py
exec.goenv(path.dirname(view.file_name()))
```

Also, just a few more questions so I can replicate your issue

- Do you have `"shell_environment": true` in your global sublime settings?
- When you run `go env` from the CLI, do you see the `GOPATH=` set correctly?

A way to reproduce this would be super helpful.

**Comment by sha256x** [comment]
running `exec.goenv(path.dirname(view.file_name()))` provides the following
- GOPATH: `"GOPATH": "/Users/<user>/go"`
- `"PATH"` does not contain the `GOPATH`

I do have `"shell_environment": true`.

runing `go env` produces the correct go path:
- `GOPATH="/Users/<user>/code/go/"`

**Comment by yields** [comment]
Thanks for the info, I'll have some time this weekend and try to reproduce this.

**Comment by sha256x** [comment]
👍

**Comment by yields** [comment]
@sha256x 

I've removed `$GOPATH` locally from `$GOPATH` and started sublime text with the latest release `v0.0.5`, looks like all the tooling works.

Can you try it out and report back please?

If that doesn't work, I wonder ST is caching the `exec` module so it wasn't actually updated, try and restart sublime after installing.

**Comment by sha256x** [comment]
Seems like the update did the trick. Thanks!
