### ISSUE TITLE
Auto-Complete Suggestions

### ISSUE THREAD

**Issue by sha256x** [yields/sublime-go#17]
Not sure if this is a feature that either doesn't yet exist or should exist, but requires some work still. But it would be nice if suggestions would show up in line while typing out something.

As an example, take the following code:

```
package main


type Test struct {
	Name string
}

var t = Test

```

When typing `Test.`, it should show a drop down, auto-suggest of "Name" without having to type "Test.N" to wait for the auto-suggest.

Currently it does the following: https://imgur.com/a/gFnNje4
It would be great if it showed all available fields or functions just after you type the period.

**Comment by yields** [comment]
You can add a auto_complete_trigger to your main sublime settings:

```
	"auto_complete_triggers":
	[
		{
			"characters": "<",
			"selector": "text.html"
		},
		{
			"characters": ".",
			"selector": "source.go"
		}
	],
```
