### ISSUE TITLE
Provide settings i.e. to configure paths, testing settings

### ISSUE THREAD

**Issue by piotrkubisa** [yields/sublime-go#21]
As a user I'd like to have own settings file where I will be able to change paths to binaries (i.e. `golint`) or parameters passed when using a `go test` command (e.g. to ignore caching).

**Comment by yields** [comment]
hmm yeah I started on it kinda, I'll have to to finish this up, maybe this weekend, see `conf.py` if you would like to contribute! :)

**Comment by piotrkubisa** [comment]
Oh, great! I was looking a code where I could hook some configuration into (// I was only scanning the code in the package).

**Comment by yields** [comment]
@piotrkubisa I've added a settings file in the last release, lmk if you had any settings in mind, currently can't think of any that id'e want haha

**Comment by yields** [comment]
Closing for now, feel free to re-open if you have any settings you'd like to see :)
