### ISSUE TITLE
don't want go vet, can't disable it

### ISSUE THREAD

**Issue by s-mang** [yields/sublime-go#37]
it would be great if i could disable go vet on save. 
i want to save often to get the `goimports`/`gofmt`, but the inline `go vet` on every save is just too much for me in many cases; especially when i'm piecing together a large new code change.

i would like a sublime settings file where i can disable `go vet` on save with a boolean.

**Comment by yields** [comment]
Yeah, it's annoying when refactoring for me as well, but I still want it to run on save.

I'm trying to understand the feature request here, do you want just a flag to disable `go vet` on save, or are you just annoyed by the inline errors?

**Comment by s-mang** [comment]
hey, thanks for the quick response.
both, honestly. i want to disable `go vet` with a flag, or a boolean in a sublime settings file, because the inline errors are annoying.
_(note also that I noticed that this plugin has no sublime settings file? or maybe there's a bug in the path/to/file)_

ideally i think the errors would appear as a dot to the left of the line where you hover over the dot to see the `vet` error. i think that's a common practice, or i've seen it with other sublime plugins.

but i figured an option/flag/setting to disable `go vet` completely would be easier to build in, and thus a saner request to make. then i could just run `go vet` on my own when i need to.

**Comment by yields** [comment]
> ideally i think the errors would appear as a dot to the left of the line where you hover over the dot to see the `vet` error. i think that's a common practice, or i've seen it with other sublime plugins.

This is actually the initial implementation, however it was super annoying to use the touchpad just to see the error.

I'm actually on board with adding this as an option as well.

> (note also that I noticed that this plugin has no sublime settings file? or maybe there's a bug in the path/to/file)

There is a settings file, however there's no setting to disable `vet` yet.

**Comment by schmurfy** [comment]
I just switched from GoSublime which is not really reponsive and hangs often from me to this extension and I really like it but I would love to disable running `go vet` on save automatically since it sometimes timeout, I prefer to run it on demand when I want to.

**Comment by yields** [comment]
Makes sense, I hope I'll find some time this weekend to add that setting.

**Comment by yields** [comment]
I just released `v0.1.4` which adds a `vet.run_on_post_save` flag (defaults to `true`), you can reach the settings by calling `Go: settings` from the command pallet.

**Comment by s-mang** [comment]
thank you!
